capitals = [
    {"Norway": "Oslo"},
    {"Sweden": "Stockholm"},
    {"Denmark": "Copenhagen"},
    {"Finland": "Helsinki"},
    {"Iceland": "Reykjavik"},
    {"Germany": "Berlin"},
    {"France": "Paris"},
    {"Spain": "Madrid"},
    {"Portugal": "Lisbon"},
    {"Italy": "Rome"},
    {"Belgium": "Brussels"},
    {"Netherlands": "Amsterdam"},
    {"Luxembourg": "Luxembourg"},
    {"Austria": "Vienna"},
    {"Switzerland": "Bern"},
    {"Poland": "Warsaw"},
    {"Czech Republic": "Prague"},
    {"Slovakia": "Bratislava"},
    {"Hungary": "Budapest"},
    {"Slovenia": "Ljubljana"},
    {"Croatia": "Zagreb"},
    {"Bosnia and Herzegovina": "Sarajevo"},
    {"Serbia": "Belgrade"},
    {"Montenegro": "Podgorica"},
    {"Kosovo": "Pristina"},
    {"Albania": "Tirana"},
    {"Greece": "Athens"},
    {"Bulgaria": "Sofia"},
    {"Romania": "Bucharest"},
    {"Moldova": "Chisinau"},
    {"Ukraine": "Kyiv"},
    {"Belarus": "Minsk"},
    {"Lithuania": "Vilnius"},
    {"Latvia": "Riga"},
    {"Estonia": "Tallinn"},
    {"Ireland": "Dublin"},
    {"United Kingdom": "London"},
    {"Malta": "Valletta"},
    {"Cyprus": "Nicosia"},
    {"North Macedonia": "Skopje"}
]

capitals_norsk = [
    {"Norge": "Oslo"},
    {"Sverige": "Stockholm"},
    {"Danmark": "København"},
    {"Finland": "Helsingfors"},
    {"Island": "Reykjavik"},
    {"Tyskland": "Berlin"},
    {"Frankrike": "Paris"},
    {"Spania": "Madrid"},
    {"Portugal": "Lisboa"},
    {"Italia": "Roma"},
    {"Belgia": "Brussel"},
    {"Nederland": "Amsterdam"},
    {"Luxembourg": "Luxembourg"},
    {"Østerrike": "Wien"},
    {"Sveits": "Bern"},
    {"Polen": "Warszawa"},
    {"Tsjekkia": "Praha"},
    {"Slovakia": "Bratislava"},
    {"Ungarn": "Budapest"},
    {"Slovenia": "Ljubljana"},
    {"Kroatia": "Zagreb"},
    {"Bosnia-Hercegovina": "Sarajevo"},
    {"Serbia": "Beograd"},
    {"Montenegro": "Podgorica"},
    {"Kosovo": "Pristina"},
    {"Albania": "Tirana"},
    {"Hellas": "Aten"},
    {"Bulgaria": "Sofia"},
    {"Romania": "Bucuresti"},
    {"Moldova": "Chisinau"},
    {"Ukraina": "Kyiv"},
    {"Hviterussland": "Minsk"},
    {"Litauen": "Vilnius"},
    {"Latvia": "Riga"},
    {"Estland": "Tallinn"},
    {"Irland": "Dublin"},
    {"Storbritannia": "London"},
    {"Malta": "Valletta"},
    {"Kypros": "Nikosia"},
    {"Nord-Makedonia": "Skopje"}
]
